# Generated by Django 4.1 on 2022-08-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=127)),
                ('name', models.CharField(max_length=127)),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
                ('denomination', models.IntegerField()),
            ],
        ),
    ]
